apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: postgresql
  description: PostgreSQL database for platform persistence
  tags:
    - database
    - postgresql
spec:
  type: database
  owner: group:default/developers
  system: infrastructure-ai-platform
