apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: infrastructure-ai-templates
  description: Infrastructure AI Platform Templates
  annotations:
    backstage.io/managed-by-location: url:https://github.com/giovanemere/demo-infra-ai-agent-template-idp/blob/main/catalog-info.yaml
spec:
  targets:
    - ./templates/**/template.yaml
    - ./entities/**/*.yaml
    - ./components/**/*.yaml
    - ./projects/**/catalog-info.yaml
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: infrastructure-ai-platform
  description: AI-powered infrastructure analysis and template generation
  tags:
    - ai
    - infrastructure
    - platform
spec:
  owner: group:default/developers
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ai-agent
  description: AI Agent for processing infrastructure descriptions
  annotations:
    github.com/project-slug: giovanemere/demo-infra-ai-agent
    backstage.io/techdocs-ref: dir:.
  tags:
    - ai
    - backend
    - python
spec:
  type: service
  lifecycle: production
  owner: group:default/developers
  system: infrastructure-ai-platform
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-idp
  description: Backstage Internal Developer Platform
  annotations:
    github.com/project-slug: giovanemere/demo-infra-backstage
    backstage.io/techdocs-ref: dir:.
  tags:
    - platform
    - frontend
    - typescript
spec:
  type: website
  lifecycle: production
  owner: group:default/developers
  system: infrastructure-ai-platform
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: developers
  description: Development team for Infrastructure AI Platform
spec:
  type: team
  children: []
