apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: example-web-app
  description: Aplicación web de ejemplo generada por AI Agent
  annotations:
    aws.com/cost-center: free-tier-audit
    backstage.io/managed-by-location: url:https://github.com/giovanemere/demo-infra-ai-agent-template-idp/blob/main/entities/example-web-app.yaml
spec:
  type: service
  lifecycle: experimental
  owner: platform-team
  system: infrastructure-ai-platform
  dependsOn:
    - resource:s3-storage
    - component:cloudfront-cdn
    - component:lambda-function
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: s3-storage
  description: S3 bucket para archivos estáticos
  annotations:
    aws.com/cost-center: free-tier-audit
    aws.com/service-type: s3
spec:
  type: storage
  owner: platform-team
  system: infrastructure-ai-platform
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: cloudfront-cdn
  description: CloudFront distribution para CDN
  annotations:
    aws.com/cost-center: free-tier-audit
    aws.com/service-type: cloudfront
spec:
  type: cdn
  lifecycle: experimental
  owner: platform-team
  system: infrastructure-ai-platform
  dependsOn:
    - resource:s3-storage
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: lambda-function
  description: Lambda function serverless
  annotations:
    aws.com/cost-center: free-tier-audit
    aws.com/service-type: lambda
spec:
  type: service
  lifecycle: experimental
  owner: platform-team
  system: infrastructure-ai-platform
