apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: postgresql
  description: PostgreSQL database for Backstage and AI Agent
  tags:
    - database
    - postgresql
spec:
  type: database
  lifecycle: production
  owner: developers
  system: infrastructure-ai-platform
