apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: ai-infrastructure-project
  title: AI Infrastructure Project
  description: Create a new infrastructure project analyzed by AI
  tags:
    - recommended
    - ai
    - infrastructure
    - aws
spec:
  owner: group:default/developers
  type: service
  parameters:
    - title: Project Information
      required:
        - name
        - description
      properties:
        name:
          title: Name
          type: string
          description: Unique name for the project
          pattern: '^[a-zA-Z0-9-]+$'
        description:
          title: Description
          type: string
          description: Description of the infrastructure
        owner:
          title: Owner
          type: string
          description: Owner of the component
          default: group:default/developers
        technology:
          title: Technology
          type: string
          description: Primary technology
          default: aws
          enum:
            - aws
            - azure
            - gcp
            - kubernetes
  steps:
    - id: template
      name: Fetch Skeleton
      action: fetch:template
      input:
        url: ./content
        values:
          name: ${{ parameters.name }}
          description: ${{ parameters.description }}
          owner: ${{ parameters.owner }}
          technology: ${{ parameters.technology }}
    - id: publish
      name: Publish
      action: publish:github
      input:
        allowedHosts: ['github.com']
        description: This is ${{ parameters.name }}
        repoUrl: github.com?owner=JuanFachas&repo=${{ parameters.name }}
    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'
  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
