apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ai-agent
  description: AI Agent for processing infrastructure descriptions using Gemini API
  tags:
    - ai
    - backend
    - python
    - fastapi
  annotations:
    github.com/project-slug: giovanemere/demo-infra-ai-agent
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: production
  owner: developers
  system: infrastructure-ai-platform
  providesApis:
    - ai-agent-api
  dependsOn:
    - resource:gemini-api
    - resource:postgresql
