apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-idp
  description: Backstage Internal Developer Platform for catalog management
  tags:
    - platform
    - frontend
    - typescript
    - react
  annotations:
    github.com/project-slug: giovanemere/demo-infra-backstage
    backstage.io/techdocs-ref: dir:.
spec:
  type: website
  lifecycle: production
  owner: developers
  system: infrastructure-ai-platform
  consumesApis:
    - github-api
  dependsOn:
    - resource:postgresql
