apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ai-agent-api
  description: REST API for AI-powered infrastructure analysis
  tags:
    - rest
    - ai
    - infrastructure
spec:
  type: openapi
  lifecycle: production
  owner: developers
  system: infrastructure-ai-platform
  definition: |
    openapi: 3.0.0
    info:
      title: AI Agent API
      version: 1.0.0
      description: API for processing infrastructure descriptions with AI
    paths:
      /process-text:
        post:
          summary: Process text description
          description: Analyze infrastructure description and generate Backstage YAML
      /process-image:
        post:
          summary: Process image
          description: Analyze infrastructure diagram and generate Backstage YAML
